### ISSUE TITLE
רקע לאפליקציה 

### ISSUE THREAD

**Issue by Kimt18** [ramat84/splatil#10]

**Comment by Kimt18** [comment]
טוב אז הbackground של האפליקציה שתהיה כמו קיר אפור כהה כזה עם לבנים וכמו שפריצים של ספלטון על זה ואפשר להוסיף באמצע ספלאטון ישראל כזה למרות שלא חייב תלוי איך זה ישתלב

**Comment by ramat84** [comment]
הכנת את הרקע?

**Comment by ramat84** [comment]
No background was provided
